apiVersion: v1
kind: Namespace
metadata:
  name: guestbook-dev
  labels:
    environment: dev

---
apiVersion: v1
kind: Namespace
metadata:
  name: guestbook-staging
  labels:
    environment: staging

---
apiVersion: v1
kind: Namespace
metadata:
  name: guestbook-prod
  labels:
    environment: production